@startuml Class Diagram Mark 1 - Page 1
title Endobiotic UML Class Digram - Mark 1\nPage 3: Enums\n<color:Gray>Monstrous | Endobiotic | 04/2/2023</color>

package Scripts <<Folder>>
{
    package Enums <<Folder>>
    {
        package Character <<Folder>>
        {
            enum Form 
            {
                +Manipulator
                +Transport
                +Magnetic
                +Electronic
                +Destroyer
                +Battery
                +Crab
            }
        }
        
        package GameManagers <<Folder>> 
        {
            package TimerManager <<Folder>> 
            {
                enum TimerMode
                {
                    +CountUp
                    +CountDown
                }
            }
        }

        package Interactables <<Folder>>
        {
            enum InteractableOjbects 
            {
                +Pit
            }
        }

        package Movement <<Folder>>
        {
            enum MoveDirection 
            {
                +Down
                +Up
                +Left
                +Right
            }
        }
    }
}

@enduml