@startuml Class Diagram Mark 1 - Page 2
title Endobiotic UML Class Digram - Mark 1\nPage 2: Cutscenses\n<color:Gray>Monstrous | Endobiotic | 04/2/2023</color>

package Scripts <<Folder>>
{
    package Cutscenes <<Folder>> 
    {
        class RebirthCutscene 
        {
            <b>Special Effect
            -m_rebirthParticles: ParticleSystem

            ===
            <b>Boolean Flag Scriptable Object - Player Manager
            -m_booleanFlagGlobalVariablePlayerCanMove: BooleanFlagGlobalVariableScriptableObject

            ===
            <b>Unity Methods
            -Start(): void

            ===
            Cutscene Methods
            -playRebirthCutscene(): IEnumerator
        }
    }
}

@enduml