@startuml Class Diagram Mark 1 - Page 16: ScriptableObject - Game Events - GameManagers - AudioManager
title Endobiotic UML Class Digram - Mark 1\nPage 16: ScriptableObject - Game Events - GameManagers - AudioManager\n<color:Gray>Monstrous | Endobiotic | 04/2/2023</color>

package Scripts <<Folder>>
{
   package ScriptableObject <<Folder>> 
    {
        package GameEvents <<Folder>> 
        {
             package GameManager <<Folder>> 
            {
                package AudioManager <<Folder>> 
                {
                    package AudioData <<Folder>> 
                    {
                        class AudioDataGameEventScriptableObject 
                        {
                             <b>Class Variables
                            -m_listeners: AudioDataGameEventListener

                            ===
                            <b>Registration Listener
                            +RegisterListener(AudioDataGameEventListener listener): void
                            +UnregisterListener(AudioDataGameEventListener listener): void

                            ===
                            <b>Raise/Invoke Game Events
                            +Raise(AudioDataScriptableObject a_audioData): void
                        }

                        class AudioDataGameEventListener 
                        {
                            <b>Game Event Scriptable Object
                            -m_gameEvent: AudioDataScriptableObject

                            ===
                            <b>Unity Event
                            -m_response: UnityEvent<AudioDataScriptableObject>

                            ===
                            <b>Invoke Unity Events
                            +OnEventRaised(AudioDataScriptableObject a_audioData): void

                            ===
                            <b>Unity Methods
                            -OnEnable(): void
                            -nDisable(): void
                        }
                    }

                    package AudioList <<Folder>> 
                    {
                         class AudioListGameEventScritableObject 
                        {
                             <b>Class Variables
                            -m_listeners: AudioListGameEventListener

                            ===
                            <b>Registration Listener
                            +RegisterListener(AudioListGameEventListener listener): void
                            +UnregisterListener(AudioListGameEventListener listener): void

                            ===
                            <b>Raise/Invoke Game Events
                            +Raise(AudioListScriptableObject a_audioList): void
                        }

                        class AudioListGameEventListener 
                        {
                            <b>Game Event Scriptable Object
                            -m_gameEvent: AudioListGameEventScritableObject

                            ===
                            <b>Unity Event
                            -m_response: UnityEvent<AudioListScriptableObject>

                            ===
                            <b>Invoke Unity Events
                            +OnEventRaised(AudioListScriptableObject a_audioList): void

                            ===
                            <b>Unity Methods
                            -OnEnable(): void
                            -nDisable(): void
                        }
                    }
                }
            }
        }
    } 
}

@enduml