@startuml Class Diagram Mark 1 - Page 10
title Endobiotic UML Class Digram - Mark 1\nPage 10: ScriptableObject - Game Events - GameManagers - LevelManager\n<color:Gray>Monstrous | Endobiotic | 04/2/2023</color>

package Scripts <<Folder>>
{
   package ScriptableObject <<Folder>> 
    {
        package GameEvents <<Folder>> 
        {
            package GameManager <<Folder>> 
            {
                package LevelManager <<Folder>>
                {
                    package LevelData <<Folder>> 
                    {
                        class LevelDataGameEventScriptableObject 
                        {
                             <b>Class Variables
                            -m_listeners: LevelDataGameEventListener

                            ===
                            <b>Registration Listener
                            +RegisterListener(LevelDataGameEventListener listener): void
                            +UnregisterListener(LevelDataGameEventListener listener): void

                            ===
                            <b>Raise/Invoke Game Events
                            +Raise(LevelDataGameEventScriptableObject a_levelData): void
                        }

                        class LevelDataGameEventListener 
                        {
                            <b>Game Event Scriptable Object
                            -m_gameEvent: LevelDataGameEventListener

                            ===
                            <b>Unity Event
                            -m_response: UnityEvent<LevelDataScriptableObject>

                            ===
                            <b>Invoke Unity Events
                            +OnEventRaised(LevelDataGameEventScriptableObject a_levelData): void

                            ===
                            <b>Unity Methods
                            -OnEnable(): void
                            -nDisable(): void
                        }
                    }
                }
            }
        }
    } 
}

@enduml