@startuml Class Diagram Mark 1 - Page 14
title Endobiotic UML Class Digram - Mark 1\nPage 14: ScriptableObject - ID\n<color:Gray>Monstrous | Endobiotic | 04/2/2023</color>

package Scripts <<Folder>>
{
    package ScriptableObject <<Folder>> 
    {
        package ID <<Folder>> 
        {
            class GuildIDScriptableObject 
            {
                <b>Class Variables
                -m_guildID: string

                ===
                <b>Generate Methods
                +GenerateID(): void
            }
        }
    } 
}

@enduml