@startuml Class Diagram Mark 1 - Page 13: ScriptableObject - Lists
title Endobiotic UML Class Digram - Mark 1\nPage 13: ScriptableObject - Lists\n<color:Gray>Monstrous | Endobiotic | 04/2/2023</color>

package Scripts <<Folder>>
{
    package Lists <<Folder>> 
    {
        class AudioListScriptableObject
        {
            <b>Class Variables
            -m_audioDatas: List<AudioDataScriptableObject>

            ===
            <b>Getters and Setters
            +audioDatas: List<AudioDataScriptableObject>
        }

        class LevelListScriptableObject 
        {
            <b>Class Variables
            -m_levelDatas: List<LevelDataScriptableObject>

            ===
            <b>Getters and Setters
            +levelDatas: List<LevelDataScriptableObject>
            +GetLevelById(string a_id): int
        }
    }
}

@enduml